insert into product (title, description, price, image) values ('Mint - Fresh', 'Action|Crime|Drama', 40, 'http://dummyimage.com/205x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Carbonated Water - Blackcherry', 'Drama|Fantasy|Mystery', 40, 'http://dummyimage.com/191x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Bread - Raisin Walnut Pull', 'Animation|Comedy|Fantasy', 84, 'http://dummyimage.com/192x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Table Cloth 90x90 White', 'Drama', 95, 'http://dummyimage.com/157x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Tortillas - Flour, 12', 'Drama', 35, 'http://dummyimage.com/232x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Napkin - Beverge, White 2 - Ply', 'Documentary', 13, 'http://dummyimage.com/101x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Yoghurt Tubes', 'Comedy|Drama', 39, 'http://dummyimage.com/155x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Table Cloth 62x114 Colour', 'Sci-Fi', 7, 'http://dummyimage.com/174x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Russian Prince', 'Adventure|Animation|Children|Comedy', 46, 'http://dummyimage.com/111x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Rosemary - Fresh', 'Comedy', 22, 'http://dummyimage.com/180x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Blueberries - Frozen', 'Comedy|Thriller', 22, 'http://dummyimage.com/166x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Bacardi Limon', 'Comedy|Drama', 79, 'http://dummyimage.com/154x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Asparagus - White, Canned', 'Animation|Children|Comedy|Musical', 73, 'http://dummyimage.com/115x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Beans - Black Bean, Dry', 'Comedy', 75, 'http://dummyimage.com/169x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Nut - Cashews, Whole, Raw', '(no genres listed)', 39, 'http://dummyimage.com/183x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Beer - Rickards Red', 'Action|Drama|Sci-Fi|Thriller', 18, 'http://dummyimage.com/135x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Beef - Ox Tongue, Pickled', 'Drama', 73, 'http://dummyimage.com/218x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Olives - Morracan Dired', 'Drama', 20, 'http://dummyimage.com/181x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Sauce - Apple, Unsweetened', 'Comedy', 7, 'http://dummyimage.com/170x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Vodka - Hot, Lnferno', 'Crime|Drama|Mystery', 60, 'http://dummyimage.com/166x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Gatorade - Lemon Lime', 'Documentary|IMAX', 94, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Crab - Imitation Flakes', 'Comedy|Musical|Romance', 43, 'http://dummyimage.com/121x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Cheese - Cambozola', 'Documentary', 23, 'http://dummyimage.com/142x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Potatoes - Idaho 100 Count', 'Comedy|Drama', 19, 'http://dummyimage.com/109x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Pepper - Chili Powder', 'Comedy|Drama|Romance', 18, 'http://dummyimage.com/144x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Lotus Rootlets - Canned', 'Drama|Sci-Fi', 98, 'http://dummyimage.com/230x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Milk - Chocolate 500ml', 'Horror', 78, 'http://dummyimage.com/199x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Compound - Pear', 'Comedy', 69, 'http://dummyimage.com/196x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Chips Potato All Dressed - 43g', 'Adventure|Drama', 11, 'http://dummyimage.com/169x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Veal - Heart', 'Drama|Film-Noir|Thriller', 57, 'http://dummyimage.com/170x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Onions - Dried, Chopped', 'Drama', 56, 'http://dummyimage.com/123x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Cookies - Englishbay Wht', 'Comedy|Romance', 39, 'http://dummyimage.com/227x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Milk - 2%', 'Comedy', 48, 'http://dummyimage.com/181x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Sprouts - Pea', 'Action|Adventure|Comedy|Western', 98, 'http://dummyimage.com/241x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Wine - Masi Valpolocell', 'Drama|Thriller', 25, 'http://dummyimage.com/126x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Wiberg Cure', 'Documentary', 72, 'http://dummyimage.com/161x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Beer - Mill St Organic', 'Comedy|Drama', 98, 'http://dummyimage.com/146x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Doilies - 5, Paper', 'Western', 27, 'http://dummyimage.com/178x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Wine - Cabernet Sauvignon', 'Animation|Comedy', 56, 'http://dummyimage.com/133x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Pasta - Elbows, Macaroni, Dry', 'Comedy', 77, 'http://dummyimage.com/212x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Bread - Dark Rye', 'Horror|Mystery', 68, 'http://dummyimage.com/199x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Cognac - Courvaisier', 'Documentary', 31, 'http://dummyimage.com/197x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Cookies - Englishbay Oatmeal', 'Mystery', 86, 'http://dummyimage.com/168x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Coffee Cup 12oz 5342cd', 'Drama', 26, 'http://dummyimage.com/207x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Pepper - Gypsy Pepper', 'Horror|Thriller', 76, 'http://dummyimage.com/117x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Red Snapper - Fillet, Skin On', 'Documentary', 34, 'http://dummyimage.com/233x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Chickhen - Chicken Phyllo', 'Comedy|Crime', 30, 'http://dummyimage.com/121x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Olives - Kalamata', 'Drama|Romance', 24, 'http://dummyimage.com/160x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Cilantro / Coriander - Fresh', 'Comedy|Drama', 34, 'http://dummyimage.com/243x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Compound - Mocha', 'Comedy|Drama|Romance', 17, 'http://dummyimage.com/164x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Sherbet - Raspberry', 'Comedy', 73, 'http://dummyimage.com/248x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Quail - Jumbo', 'Comedy', 38, 'http://dummyimage.com/206x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Hot Choc Vending', 'Children|Comedy|Drama', 62, 'http://dummyimage.com/157x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Onions - Red Pearl', 'Drama', 34, 'http://dummyimage.com/144x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Bouillion - Fish', 'Comedy|Drama|Romance', 22, 'http://dummyimage.com/246x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Five Alive Citrus', 'Drama', 39, 'http://dummyimage.com/204x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Rum - Mount Gay Eclipes', 'Children', 59, 'http://dummyimage.com/236x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Irish Cream - Baileys', 'Action|Adventure|Drama|War', 86, 'http://dummyimage.com/189x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Juice - Happy Planet', 'Crime|Documentary', 39, 'http://dummyimage.com/126x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Bread - Hot Dog Buns', 'Drama', 19, 'http://dummyimage.com/117x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Juice - Apple 284ml', 'Comedy|Horror', 20, 'http://dummyimage.com/108x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Chinese Foods - Chicken', 'Action|Horror|Thriller', 3, 'http://dummyimage.com/109x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Lamb - Whole Head Off', 'Horror', 14, 'http://dummyimage.com/213x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Onions - Green', 'Horror|Mystery', 22, 'http://dummyimage.com/154x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Rum - Light, Captain Morgan', 'Comedy|Drama|Romance', 63, 'http://dummyimage.com/131x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Turkey Tenderloin Frozen', 'Adventure|Documentary', 97, 'http://dummyimage.com/120x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Muffin Hinge Container 6', 'Comedy|Romance', 51, 'http://dummyimage.com/140x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Sobe - Cranberry Grapefruit', 'Comedy|Drama|Romance', 32, 'http://dummyimage.com/109x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Icecream - Dstk Strw Chseck', 'Action|Comedy', 11, 'http://dummyimage.com/112x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Cheese - Shred Cheddar / Mozza', 'Documentary', 29, 'http://dummyimage.com/131x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Coffee Guatemala Dark', 'Adventure|Children', 21, 'http://dummyimage.com/152x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Sauce - Sesame Thai Dressing', 'Comedy', 83, 'http://dummyimage.com/137x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Huck White Towels', 'Comedy|Drama|Fantasy', 86, 'http://dummyimage.com/119x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Sour Cream', 'Comedy', 57, 'http://dummyimage.com/156x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Bagel - 12 Grain Preslice', 'Comedy|Drama|Romance', 36, 'http://dummyimage.com/234x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Cookies - Amaretto', 'Comedy', 40, 'http://dummyimage.com/244x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Mushroom - Chanterelle Frozen', 'Comedy|Musical', 55, 'http://dummyimage.com/234x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Wine - Touraine Azay - Le - Rideau', 'Drama', 16, 'http://dummyimage.com/203x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Pie Filling - Cherry', 'Drama', 76, 'http://dummyimage.com/248x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Cheese - Swiss', 'Action|Drama|Thriller', 58, 'http://dummyimage.com/124x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Ham Black Forest', 'Comedy|Drama', 56, 'http://dummyimage.com/154x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Pasta - Elbows, Macaroni, Dry', 'Animation|Musical', 64, 'http://dummyimage.com/148x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Asparagus - White, Canned', 'Horror', 100, 'http://dummyimage.com/165x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('The Pop Shoppe - Root Beer', 'Animation|Comedy', 72, 'http://dummyimage.com/207x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Ostrich - Prime Cut', 'Action|Horror|Thriller', 8, 'http://dummyimage.com/127x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Melon - Watermelon Yellow', 'Horror', 87, 'http://dummyimage.com/144x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Dates', 'Action|Adventure|Animation', 21, 'http://dummyimage.com/173x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Mustard - Dry, Powder', 'Action|Fantasy|Sci-Fi', 17, 'http://dummyimage.com/113x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Apricots Fresh', 'Comedy|Drama', 55, 'http://dummyimage.com/245x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Pickles - Gherkins', 'Action|Sci-Fi', 87, 'http://dummyimage.com/241x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Soda Water - Club Soda, 355 Ml', 'Action|Crime|Thriller', 87, 'http://dummyimage.com/186x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Soup - Beef, Base Mix', 'Documentary', 36, 'http://dummyimage.com/130x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Cake - Sheet Strawberry', 'Comedy', 77, 'http://dummyimage.com/247x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Nectarines', 'Drama', 31, 'http://dummyimage.com/225x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Sugar - Cubes', 'Fantasy|Horror', 31, 'http://dummyimage.com/151x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Liqueur Banana, Ramazzotti', 'Documentary', 83, 'http://dummyimage.com/174x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Hickory Smoke, Liquid', 'Comedy|Romance', 83, 'http://dummyimage.com/118x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Tart Shells - Barquettes, Savory', 'Drama|Romance', 17, 'http://dummyimage.com/112x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Nut - Almond, Blanched, Whole', 'Comedy|Crime', 86, 'http://dummyimage.com/107x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Tea - Grapefruit Green Tea', 'Action|Fantasy|War|IMAX', 91, 'http://dummyimage.com/195x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Pastrami', 'Animation|Children', 96, 'http://dummyimage.com/237x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Banana', 'Action|Horror|Thriller', 53, 'http://dummyimage.com/104x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Pepsi, 355 Ml', 'Comedy|Drama|Romance', 64, 'http://dummyimage.com/181x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Bagelers - Cinn / Brown', 'Comedy|Romance', 50, 'http://dummyimage.com/223x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Steampan - Foil', 'Action|Adventure|Comedy|Crime|Romance|Thriller', 52, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Icecream - Dstk Strw Chseck', 'Comedy', 36, 'http://dummyimage.com/138x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Edible Flower - Mixed', 'Fantasy|Horror|Sci-Fi', 82, 'http://dummyimage.com/223x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Cake - Lemon Chiffon', 'Drama|Mystery', 61, 'http://dummyimage.com/110x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Veal - Provimi Inside', 'Documentary', 95, 'http://dummyimage.com/145x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Soup - Campbells, Spinach Crm', 'Adventure|Comedy', 33, 'http://dummyimage.com/166x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Sauce - Alfredo', 'Action|Adventure|Comedy|Sci-Fi', 96, 'http://dummyimage.com/230x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Bay Leaf Ground', 'Drama', 100, 'http://dummyimage.com/134x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Pepper - Yellow Bell', 'Horror|Thriller', 52, 'http://dummyimage.com/246x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Pastrami', 'Action|Sci-Fi', 52, 'http://dummyimage.com/125x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Cheese - Cheddar With Claret', 'Documentary', 16, 'http://dummyimage.com/196x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Gherkin - Sour', 'Comedy', 1, 'http://dummyimage.com/151x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Puree - Pear', 'Comedy|Horror', 69, 'http://dummyimage.com/138x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Bagel - Whole White Sesame', '(no genres listed)', 95, 'http://dummyimage.com/194x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Black Currants', 'Comedy', 61, 'http://dummyimage.com/165x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Wine - Savigny - Les - Beaune', 'Comedy', 50, 'http://dummyimage.com/123x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Cup Translucent 9 Oz', 'Action|Adventure|Drama', 42, 'http://dummyimage.com/110x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Crab - Dungeness, Whole', 'Adventure|Comedy|Fantasy', 26, 'http://dummyimage.com/117x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Wine - Niagara,vqa Reisling', 'Documentary', 5, 'http://dummyimage.com/198x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Pork Loin Cutlets', 'Comedy', 56, 'http://dummyimage.com/177x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Glucose', 'Action|Adventure', 7, 'http://dummyimage.com/220x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Onions Granulated', 'Drama|War', 82, 'http://dummyimage.com/131x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Curry Powder Madras', 'Drama|War', 17, 'http://dummyimage.com/237x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Yeast Dry - Fleischman', 'Adventure|Children|Fantasy', 62, 'http://dummyimage.com/233x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Wine - Redchard Merritt', 'Comedy|Drama|Romance', 8, 'http://dummyimage.com/154x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Peas Snow', 'Action|Drama|Romance|War', 38, 'http://dummyimage.com/166x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Tuna - Salad Premix', 'Documentary', 30, 'http://dummyimage.com/216x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Remy Red', 'Action|Drama|War', 54, 'http://dummyimage.com/162x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Wine - Trimbach Pinot Blanc', 'Crime|Drama|Thriller', 18, 'http://dummyimage.com/150x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Soupcontfoam16oz 116con', 'Comedy|Romance', 19, 'http://dummyimage.com/243x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Sauce Tomato Pouch', 'Drama|Romance', 3, 'http://dummyimage.com/127x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Muffin Mix - Morning Glory', 'Drama', 15, 'http://dummyimage.com/182x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Chicken - Livers', 'Drama', 94, 'http://dummyimage.com/194x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Puff Pastry - Slab', 'Crime|Horror|Mystery', 34, 'http://dummyimage.com/150x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Sugar - Cubes', 'Action', 60, 'http://dummyimage.com/243x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Sauce - Cranberry', 'Crime|Drama', 18, 'http://dummyimage.com/119x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Sping Loaded Cup Dispenser', 'Drama', 29, 'http://dummyimage.com/215x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Pear - Halves', 'Adventure|Animation|Children|Comedy', 27, 'http://dummyimage.com/227x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Wine - Wyndham Estate Bin 777', 'Horror|Sci-Fi', 70, 'http://dummyimage.com/103x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Coconut - Shredded, Unsweet', 'Drama', 41, 'http://dummyimage.com/239x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Foam Tray S2', 'Drama', 25, 'http://dummyimage.com/220x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Temperature Recording Station', 'Action|Animation|Sci-Fi', 53, 'http://dummyimage.com/243x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Tart Shells - Sweet, 2', 'Comedy|Drama', 79, 'http://dummyimage.com/123x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Turkey Leg With Drum And Thigh', 'Action|Crime|Drama|Thriller', 66, 'http://dummyimage.com/116x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Nantucket Orange Juice', 'Action|Comedy|Sci-Fi', 92, 'http://dummyimage.com/242x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Pork - Side Ribs', 'Action|Sci-Fi', 60, 'http://dummyimage.com/150x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Mustard - Dry, Powder', 'Drama', 36, 'http://dummyimage.com/217x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Mussels - Cultivated', 'Adventure|Animation|Children|Fantasy|Musical|Romance', 55, 'http://dummyimage.com/137x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Sauce - Cranberry', 'Action|Adventure|Animation|Fantasy', 19, 'http://dummyimage.com/122x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Coffee Cup 8oz 5338cd', 'Drama|War', 13, 'http://dummyimage.com/126x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Wine - Sicilia Igt Nero Avola', 'Drama', 76, 'http://dummyimage.com/222x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Nantucket Apple Juice', 'Comedy|Drama', 9, 'http://dummyimage.com/125x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Bread - Bistro White', 'Documentary', 63, 'http://dummyimage.com/210x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Flour Pastry Super Fine', 'Drama|Romance|War', 19, 'http://dummyimage.com/200x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Wine - Two Oceans Sauvignon', 'Comedy', 55, 'http://dummyimage.com/131x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Corn Meal', 'Action|Comedy|Crime|Thriller', 21, 'http://dummyimage.com/123x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Beef - Ox Tail, Frozen', 'Drama|War', 49, 'http://dummyimage.com/191x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Wine - Delicato Merlot', 'Thriller', 65, 'http://dummyimage.com/126x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Beer - Sleemans Cream Ale', 'Drama', 91, 'http://dummyimage.com/147x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Apple - Macintosh', 'Adventure|Animation|Children', 91, 'http://dummyimage.com/120x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Syrup - Monin, Swiss Choclate', 'Thriller', 30, 'http://dummyimage.com/162x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Flower - Commercial Spider', 'Drama', 67, 'http://dummyimage.com/153x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Longos - Grilled Veg Sandwiches', 'Action', 37, 'http://dummyimage.com/137x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Lettuce - Radicchio', 'Drama', 93, 'http://dummyimage.com/119x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Canada Dry', 'Western', 70, 'http://dummyimage.com/196x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Cheese - Wine', 'Comedy|Drama', 94, 'http://dummyimage.com/143x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Capon - Breast, Double, Wing On', 'Drama|Romance', 56, 'http://dummyimage.com/102x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Tomato - Plum With Basil', 'Drama', 65, 'http://dummyimage.com/152x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Lettuce - California Mix', 'Drama', 97, 'http://dummyimage.com/208x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Veal - Loin', 'Documentary', 96, 'http://dummyimage.com/214x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Milkettes - 2%', 'Comedy', 17, 'http://dummyimage.com/188x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Wine - Saint Emilion Calvet', 'Drama', 18, 'http://dummyimage.com/206x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Pastry - Cherry Danish - Mini', 'Comedy|Drama', 89, 'http://dummyimage.com/201x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Yeast Dry - Fleischman', 'Comedy', 75, 'http://dummyimage.com/119x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Parsley - Dried', 'Documentary', 54, 'http://dummyimage.com/152x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Bar Bran Honey Nut', 'Comedy|Drama|Romance', 75, 'http://dummyimage.com/150x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Ham - Black Forest', 'Action|Adventure|Drama|War', 40, 'http://dummyimage.com/199x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Cookie - Dough Variety', 'Action|Comedy|Drama', 42, 'http://dummyimage.com/141x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Fruit Salad Deluxe', 'Action|Drama|Thriller', 78, 'http://dummyimage.com/141x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Cheese - St. Andre', 'Documentary', 81, 'http://dummyimage.com/143x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Vinegar - Balsamic, White', 'Comedy|Horror|Thriller', 69, 'http://dummyimage.com/160x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Sugar - White Packet', 'Action|Drama|Thriller', 97, 'http://dummyimage.com/204x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Curry Powder Madras', 'Documentary', 78, 'http://dummyimage.com/246x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Pepper - Black, Whole', 'Comedy|Drama|Romance', 41, 'http://dummyimage.com/204x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Potatoes - Yukon Gold 5 Oz', 'Animation|Drama|Fantasy', 74, 'http://dummyimage.com/141x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Chocolate - White', 'Action|Sci-Fi|Thriller', 3, 'http://dummyimage.com/145x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Truffle Cups - Brown', 'Action|Crime|Mystery|Sci-Fi|Thriller', 5, 'http://dummyimage.com/174x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Lamb - Racks, Frenched', 'Action', 86, 'http://dummyimage.com/171x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Trueblue - Blueberry Cranberry', 'Animation|Documentary|Drama|Fantasy', 45, 'http://dummyimage.com/208x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Pate - Cognac', 'Action|Adventure|Comedy|Fantasy|Romance', 60, 'http://dummyimage.com/141x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Wine - Chardonnay South', 'Action|Comedy|Crime', 73, 'http://dummyimage.com/152x100.png/ff4444/ffffff');
insert into product (title, description, price, image) values ('Corn Kernels - Frozen', 'Comedy|Horror|Thriller', 54, 'http://dummyimage.com/188x100.png/cc0000/ffffff');
insert into product (title, description, price, image) values ('Cod - Salted, Boneless', '(no genres listed)', 86, 'http://dummyimage.com/204x100.png/dddddd/000000');
insert into product (title, description, price, image) values ('Chicken - Tenderloin', 'Drama', 52, 'http://dummyimage.com/182x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Pork - Ham, Virginia', 'Horror|Sci-Fi|Thriller', 52, 'http://dummyimage.com/223x100.png/5fa2dd/ffffff');
insert into product (title, description, price, image) values ('Veal - Heart', 'Action|Animation|Comedy|Crime|Drama|Mystery|Romance|Thriller', 75, 'http://dummyimage.com/134x100.png/5fa2dd/ffffff');
